Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "postgres"
  config.vm.network 'forwarded_port', guest: 5432, host: 5432, hostip: "127.0.0.1"
  config.vm.provision "shell", path: "provision.sh"
end