Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "eureca"
  config.vm.network 'forwarded_port', guest: 3000, host: 80, hostip: "127.0.0.1"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"

  
end